name: Notion to GitHub Sync

on:
  schedule:
    - cron: '*/30 * * * *'  # 30분마다 체크

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install @notionhq/client
        
      - name: Sync Notion to GitHub
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          node .github/scripts/sync.js
